//LOCALHOST
###Get all books
GET http://localhost:3000/books
content-type: application/json



###Get 1 user
GET http://localhost:3000/books/69bc9e1e89a016b2f0415a40
content-type: application/json

###Create user
POST http://localhost:3000/books HTTP/1.1
content-type: application/json

{
    "title": "Probe",
    "author": "Test",
    "publicationYear": 9999,
    "gender": "Test",
    "editorial": "test",
    "pages": 1,
    "available": true
}

###PUT user
PUT http://localhost:3000/books/ ###write id HTTP/1.1
content-type: application/json

{
    "title": "Journey to the Center of the Earth",
  "author": "Jules Verne",
  "publicationYear": 1864,
  "gender": "Science Fiction / Adventure Novel",
  "editorial": "Pierre-Jules Hetzel",
  "pages": 183,
  "available": true
}

###DETELE user
DELETE http://localhost:3000/books/ ###write id HTTP/1.1




//PRODUCTION
